### PR TITLE
A few fixes for uploading new projects.

### PR DESCRIPTION
**Pull request by tom-garratt-w**

### CODE REVIEW

**Comment by Suremaker** [comment]
Hey Tom, I will look over the weekend to fix the pipeline for the project. Thanks for making improvements!

**Comment by tom-garratt-w** [comment]
Hey, yeah you can see I'm having problems getting it to build on AppVeyor. We're doing similar stuff with dotnetcore in Jenkins Pipelines and we've wrangled OpenCover to do the dirty work, but a new PSMake dotnetcore module might be easier!

**Comment by pavlo-oliinyk** [comment]
Hey @tom-garratt-w 
I tried to fix this also. [Here](https://github.com/pavlo-oliinyk/OctopusProjectBuilder/commit/b3e1510262be924ddad23c660dead4bd1ca0fd74) are my changes to OPB. And it requires small [changes](https://github.com/Suremaker/PsMake/pull/14) in PSMake.
I could not run tests locally and have no idea where the problem is. 
Have to find some time to fix it.

**Comment by Suremaker** [comment]
Hey guys, please take a look at #17 where I sorted out the make scripts. 

I saw @pavlo-oliinyk fixes for the opencover but it's really a workaround as opencover still does not support portable pdbs. ... so instead of it, I changed the scripts to use dotcover.exe

If that will work for you, I'll merge the changes to 3.x branch... Also at some point I will merge it to master, making it default version

**Review by williamlord — APPROVED** [review]

**Pull request merged**
